# -----------------
# 内核参数
# -----------------
- name: "调整内核参数"
  ansible.posix.sysctl:
    name: "vm.overcommit_memory"
    value: "1"
    sysctl_file: /etc/sysctl.conf
    reload: true
  notify:
    - "重启Instance1服务"
    - "重启Instance2服务"

# -----------------
# 公共
# -----------------
- name: "拷贝公共配置文件"
  ansible.builtin.template:
    src: redis-included.conf
    dest: /opt/redis/etc/redis-included.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - "重启Instance1服务"
    - "重启Instance2服务"

# -----------------
# 集群 Instance1
# -----------------
- name: "拷贝Instance1配置文件"
  ansible.builtin.template:
    src: redis-instance1.conf
    dest: /opt/redis/etc/redis-{{ instance1.port }}.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - "重启Instance1服务"

- name: "拷贝Instance1服务定义文件"
  ansible.builtin.template:
    src: redis-instance1.service
    dest: /etc/systemd/system/{{ instance1.service }}.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - "重加载所有服务"
    - "重启Instance1服务"

# -----------------
# 集群 Instance2
# -----------------
- name: "拷贝Instance2配置文件"
  ansible.builtin.template:
    src: redis-instance2.conf
    dest: /opt/redis/etc/redis-{{ instance2.port }}.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - "重启Instance2服务"

- name: "拷贝Instance2服务定义文件"
  ansible.builtin.template:
    src: redis-instance2.service
    dest: /etc/systemd/system/{{ instance2.service }}.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - "重加载所有服务"
    - "重启Instance2服务"

# -----------------
# 红锁
# -----------------
- name: "拷贝红锁服务配置文件"
  ansible.builtin.template:
    src: redis-redlock.conf
    dest: /opt/redis/etc/redis-redlock.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - "重启红锁服务"

- name: "拷贝红锁服务定义文件"
  ansible.builtin.template:
    src: redis-redlock.service
    dest: /etc/systemd/system/{{ redlock.service }}.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - "重加载所有服务"
    - "重启红锁服务"
