- name: "重加载所有服务"
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "重启Instance1服务"
  ansible.builtin.service:
    name: "{{ instance1.service }}"
    state: restarted
    enabled: true

- name: "重启Instance2服务"
  ansible.builtin.service:
    name: "{{ instance2.service }}"
    state: restarted
    enabled: true

- name: "重启红锁服务"
  ansible.builtin.service:
    name: "{{ redlock.service }}"
    state: restarted
    enabled: true
