java_home: "/opt/java-home"

app_name: "playground"
app_version: "0.3.1"
app_doc_url: "https://github.com/yingzhuo/spring-boot-playground"

app_home: "/opt/playground"
app_config_dir: "/opt/playground/config"
app_bin_dir: "/opt/playground/bin"
app_lib_dir: "/opt/playground/lib"
app_log_dir: "/var/log/playground"
app_pid_dir: "/var/run"

app_heapdump_dir: ""
app_gclog_dir: ""

envs: {}

java_opts:
  - "-server -Xmixed"
  - "-XX:-PrintCommandLineFlags -XX:-PrintFlagsInitial -XX:-PrintFlagsFinal"
  - "-XX:ThreadStackSize=512k"
  - "-XX:InitialHeapSize=256m -XX:MinHeapSize=256m -XX:NewRatio=2 -XX:SurvivorRatio=8 -XX:+UseTLAB"
  - "-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:+UseCompressedOops"
  - "-XX:MaxDirectMemorySize=256m"
  - "-XX:+UseG1GC -XX:MaxGCPauseMillis=300"
  - "-XX:+UsePerfData"

spring_args:
  - "--spring.profiles.active=prod,last_override"
