- name: "检查tag"
  ansible.builtin.debug:
    msg: "[错误]没有指定tags"
  when: "ansible_run_tags == ['all']"
  failed_when: true

###############################################################################

- name: "保证日志目录"
  ansible.builtin.file:
    path: "{{ log_dir }}"
    state: directory
  tags:
    - setup

- name: "保证数据目录"
  ansible.builtin.file:
    path: "{{ data_dir }}"
    state: directory
  tags:
    - setup

- name: "拷贝启动文件"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  loop:
    - src: runbroker.sh
      dest: "{{ rocketmq_home }}/bin/runbroker.sh"
    - src: mqbroker
      dest: "{{ rocketmq_home }}/bin/mqbroker"
  notify:
    - "重加载所有服务"
    - "重启Broker"
  tags:
    - setup

- name: "拷贝主配置文件"
  ansible.builtin.template:
    src: broker-this.properties
    dest: "{{ rocketmq_home }}/conf/broker-this.properties"
    owner: root
    group: root
  notify:
    - "重启Broker"
  tags:
    - setup

- name: "拷贝logback文件"
  ansible.builtin.template:
    src: rmq.broker.logback.xml
    dest: "{{ rocketmq_home }}/conf/rmq.broker.logback.xml"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
      - "重启Broker"
  tags:
      - setup

- name: "拷贝服务定义文件"
  ansible.builtin.template:
    src: rocketmq-broker.service
    dest: /etc/systemd/system/rocketmq-broker.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - "重加载所有服务"
    - "重启Broker"
  tags:
    - setup

###############################################################################

- name: "关闭RocketMQ服务 (Broker)"
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - "rocketmq-broker"
  tags: 
    - stop

###############################################################################

- name: "开启RocketMQ服务 (Broker)"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - "rocketmq-broker"
  tags: 
    - startup

###############################################################################

- name: "重启RocketMQ服务 (Broker)"
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - "rocketmq-broker"
  tags: 
    - restart
