- name: "检查tag"
  ansible.builtin.debug:
    msg: "[错误]没有指定tags"
  when: "ansible_run_tags == ['all']"
  failed_when: true

###############################################################################

- name: "拷贝配置文件"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/mysql/mysql.conf.d/{{ item }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  loop:
    - mysqld.cnf.j2
    - mysql.cnf.j2
  notify:
    - "重启MySQL服务"
  tags:
    - setup

- name: "为数据目录创建软连接"
  ansible.builtin.file:
    src: /var/lib/mysql
    dest: /opt-data/mysql
    state: link
  tags:
    - setup

- name: "更新管理账户属组"
  ansible.builtin.user:
    name: yingzhuo
    groups:
      - mysql
    append: true
  tags:
    - setup

###############################################################################

- name: "停止MySQL服务"
  ansible.builtin.service:
    name: mysql
    state: stopped
    enabled: false
  tags:
    - stop

###############################################################################

- name: "启动MySQL服务"
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
  tags:
    - startup

###############################################################################

- name: "重启MySQL服务"
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true
  tags:
    - restart
