- name: "拷贝配置文件"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/mysql/mysql.conf.d/{{ item }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  loop:
    - mysqld.cnf
    - mysql.cnf
  notify:
    - "重启MySQL服务"
  tags: setup

- name: "更新管理账户属组"
  ansible.builtin.user:
    name: yingzhuo
    groups:
      - mysql
    append: true
  tags: setup

###############################################################################

- name: "停止MySQL服务"
  ansible.builtin.service:
    name: mysql
    state: stopped
    enabled: false
  tags: stop

###############################################################################

- name: "启动MySQL服务"
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
  tags: startup

###############################################################################

- name: "重启MySQL服务"
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true
  tags: restart
