- name: "安装必要的软件"
  ansible.builtin.apt:
    name:
      - git
      - make
      - automake
      - autoconf
      - gcc
      - g++
      - zsh
      - net-tools
      - wget
      - curl
      - cowsay
      - figlet
      - zip
      - unzip
      - libncurses5-dev
      - libncursesw5-dev
      - sysstat
      - build-essential
      - apt-transport-https
    state: present

- name: "配置sshd"
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - "重启sshd服务"

- name: "配置/tmp目录权限"
  ansible.builtin.file:
    name: /tmp/
    mode: "0777"
    state: directory

- name: "设置hostname"
  ansible.builtin.hostname:
    name: "{{ hostname_dict[ansible_host] }}"

- name: "配置防火墙"
  community.general.ufw:
    state: disabled

- name: "配置HOSTS"
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      192.168.31.165 ubuntu01
      192.168.31.166 ubuntu02
      192.168.31.167 ubuntu03
    marker: "## {mark} add hosts block by ansible"
    state: present
