java_home: "/opt/java-home"

app_name: "xxljob"
app_version: "2.4.2"

app_home: "/opt/xxljob"
app_config_dir: "/opt/xxljob/config"
app_bin_dir: "/opt/xxljob/bin"
app_lib_dir: "/opt/xxljob/lib"
app_log_dir: "/var/log/xxljob"
app_pid_dir: "/var/run"
app_heapdump_dir: ""
app_gclog_dir: ""

envs: {}

java_opts:
  - "-server -Xmixed"
  - "-XX:-PrintCommandLineFlags -XX:-PrintFlagsInitial -XX:-PrintFlagsFinal"
  - "-XX:ThreadStackSize=512k"
  - "-XX:InitialHeapSize=256m -XX:MinHeapSize=256m -XX:NewRatio=2 -XX:SurvivorRatio=8 -XX:+UseTLAB"
  - "-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:+UseCompressedOops"
  - "-XX:MaxDirectMemorySize=256m"
  - "-XX:+UseG1GC -XX:MaxGCPauseMillis=300"
  - "-XX:+UsePerfData"

spring_args: 
  - "--spring.profiles.active=default"
  - "--server.port=7055"

db:
  host: "192.168.31.165"
  port: "3306"
  username: "xxl-job"
  password: "xxl-job"

access_token: "default_token"
