- name: "拷贝配置文件 (NameServer)"
  ansible.builtin.template:
    src: runserver.sh
    dest: /opt/rocketmq/bin/runserver.sh
    owner: root
    group: root
  tags: 
    - setup
  notify:
    - "重启NameServer"

- name: "拷贝服务定义文件 (NameServer)"
  ansible.builtin.template:
    src: rocketmq-namesrv.service
    dest: /etc/systemd/system/rocketmq-namesrv.service
  tags: 
    - setup
  notify:
    - "重加载所有服务"
    - "重启NameServer"

- name: "拷贝mqbroker文件"
  ansible.builtin.template:
    src: mqbroker
    dest: /opt/rocketmq/bin/mqbroker
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  tags: 
    - setup
  notify:
    - "重加载所有服务"
    - "重启Broker"

- name: "拷贝配置文件 (Broker)"
  ansible.builtin.template:
    src: runbroker.sh
    dest: /opt/rocketmq/bin/runbroker.sh
    owner: root
    group: root
  tags: 
    - setup
  notify:
    - "重加载所有服务"
    - "重启Broker"

- name: "拷贝服务定义文件 (Broker)"
  ansible.builtin.template:
    src: rocketmq-broker.service
    dest: /etc/systemd/system/rocketmq-broker.service
  tags: 
    - setup
  notify:
    - "重加载所有服务"
    - "重启Broker"

###############################################################################

- name: "关闭rocketmq服务"
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - "rocketmq-broker"
    - "rocketmq-namesrv"
  tags: stop

###############################################################################

- name: "开启rocketmq服务"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - "rocketmq-namesrv"
    - "rocketmq-broker"
  tags: startup

###############################################################################

- name: "开启rocketmq服务"
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - "rocketmq-namesrv"
    - "rocketmq-broker"
  tags: restart
