- name: "清理不需要的文件"
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - "/home/yingzhuo/.python_history"
    - "/home/yingzhuo/.zsh_history"
    - "/home/yingzhuo/.mysql_history"
  tags: cleanup

- name: "清理upload目录"
  ansible.builtin.file:
    path: "/home/yingzhuo/uploaded/"
    state: "{{ item }}"
    owner: root
    group: root
  loop:
    - absent
    - directory
  changed_when: false
  tags: cleanup

- name: "配置vim"
  ansible.builtin.unarchive:
    src: vim.tar.gz
    dest: /home/yingzhuo/
    owner: yingzhuo
    group: yingzhuo
    mode: "u=rwx,g=rwx,o=rx"
  tags: cleanup
