- name: "检查tag"
  ansible.builtin.debug:
    msg: "[错误]没有指定tags"
  when: "ansible_run_tags == ['all']"
  failed_when: true

###############################################################################

- name: "安装一些软件"
  ansible.builtin.apt:
    name:
      - haveged
    state: present
  tags: setup

- name: "拷贝配置文件"
  ansible.builtin.template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - "重启docker服务"
  tags: setup

###############################################################################

- name: "关闭Docker服务"
  ansible.builtin.service:
    name: docker
    state: stopped
    enabled: false
  tags: stop

###############################################################################

- name: "启动Docker服务"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  tags: startup

###############################################################################

- name: "重启Docker服务"
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true
  tags: restart
